
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Jin
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form conversorPantalla
     */
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaError = new javax.swing.JDialog();
        jpinterfazError = new javax.swing.JPanel();
        jpventana3 = new javax.swing.JPanel();
        jlcerrarError = new javax.swing.JLabel();
        jltituloError = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ventanaResultado = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jlmessageResultado = new javax.swing.JLabel();
        jlmessageResultado1 = new javax.swing.JLabel();
        jpventana4 = new javax.swing.JPanel();
        jlcerrarResultado = new javax.swing.JLabel();
        jltituloResultado = new javax.swing.JLabel();
        jpinterfaz = new javax.swing.JPanel();
        jpventana = new javax.swing.JPanel();
        jltitulo = new javax.swing.JLabel();
        jlcerrarVentana = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtgrados = new javax.swing.JTextField();
        jpaplicar = new javax.swing.JPanel();
        jlaplicar = new javax.swing.JLabel();

        ventanaError.setAlwaysOnTop(true);
        ventanaError.setBackground(new java.awt.Color(204, 204, 204));
        ventanaError.setLocationByPlatform(true);
        ventanaError.setModal(true);
        ventanaError.setUndecorated(true);
        ventanaError.setPreferredSize(new java.awt.Dimension(330, 100));
        ventanaError.setResizable(false);
        ventanaError.setSize(new java.awt.Dimension(330, 100));
        ventanaError.setType(java.awt.Window.Type.POPUP);

        jpinterfazError.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpinterfazError.setForeground(new java.awt.Color(204, 204, 204));
        jpinterfazError.setMaximumSize(new java.awt.Dimension(330, 100));
        jpinterfazError.setMinimumSize(new java.awt.Dimension(329, 99));
        jpinterfazError.setOpaque(false);
        jpinterfazError.setPreferredSize(new java.awt.Dimension(330, 100));
        jpinterfazError.setVerifyInputWhenFocusTarget(false);

        jpventana3.setBackground(new java.awt.Color(255, 51, 51));
        jpventana3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpventana3.setAlignmentX(0.0F);
        jpventana3.setAlignmentY(0.0F);
        jpventana3.setMaximumSize(new java.awt.Dimension(300, 40));
        jpventana3.setMinimumSize(new java.awt.Dimension(300, 40));
        jpventana3.setPreferredSize(new java.awt.Dimension(300, 40));

        jlcerrarError.setBackground(new java.awt.Color(0, 0, 0));
        jlcerrarError.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jlcerrarError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlcerrarError.setText("X");
        jlcerrarError.setMaximumSize(new java.awt.Dimension(40, 30));
        jlcerrarError.setMinimumSize(new java.awt.Dimension(40, 30));
        jlcerrarError.setPreferredSize(new java.awt.Dimension(40, 30));
        jlcerrarError.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlcerrarErrorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlcerrarErrorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlcerrarErrorMouseExited(evt);
            }
        });

        jltituloError.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jltituloError.setText("Error");

        javax.swing.GroupLayout jpventana3Layout = new javax.swing.GroupLayout(jpventana3);
        jpventana3.setLayout(jpventana3Layout);
        jpventana3Layout.setHorizontalGroup(
            jpventana3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpventana3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jltituloError, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(jlcerrarError, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpventana3Layout.setVerticalGroup(
            jpventana3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpventana3Layout.createSequentialGroup()
                .addComponent(jlcerrarError, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addComponent(jltituloError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingresa grados a convertir con o sin punto.");
        jLabel2.setToolTipText("Ejemplo: 32.6 o 32");

        javax.swing.GroupLayout jpinterfazErrorLayout = new javax.swing.GroupLayout(jpinterfazError);
        jpinterfazError.setLayout(jpinterfazErrorLayout);
        jpinterfazErrorLayout.setHorizontalGroup(
            jpinterfazErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpinterfazErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpinterfazErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpventana3, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
        );
        jpinterfazErrorLayout.setVerticalGroup(
            jpinterfazErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpinterfazErrorLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
            .addGroup(jpinterfazErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpinterfazErrorLayout.createSequentialGroup()
                    .addComponent(jpventana3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 58, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout ventanaErrorLayout = new javax.swing.GroupLayout(ventanaError.getContentPane());
        ventanaError.getContentPane().setLayout(ventanaErrorLayout);
        ventanaErrorLayout.setHorizontalGroup(
            ventanaErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpinterfazError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ventanaErrorLayout.setVerticalGroup(
            ventanaErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpinterfazError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ventanaResultado.setAlwaysOnTop(true);
        ventanaResultado.setBackground(new java.awt.Color(204, 204, 204));
        ventanaResultado.setLocationByPlatform(true);
        ventanaResultado.setMaximumSize(new java.awt.Dimension(330, 115));
        ventanaResultado.setMinimumSize(new java.awt.Dimension(330, 115));
        ventanaResultado.setUndecorated(true);
        ventanaResultado.setPreferredSize(new java.awt.Dimension(300, 115));
        ventanaResultado.setResizable(false);
        ventanaResultado.setSize(new java.awt.Dimension(330, 115));
        ventanaResultado.setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(330, 115));
        jPanel1.setMinimumSize(new java.awt.Dimension(330, 115));
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 115));

        jlmessageResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlmessageResultado.setText("hola");

        jlmessageResultado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlmessageResultado1.setText("Se convirtieron los grados Celsius a Fahrenheit");

        jpventana4.setBackground(new java.awt.Color(102, 102, 255));
        jpventana4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpventana4.setMaximumSize(new java.awt.Dimension(330, 40));
        jpventana4.setMinimumSize(new java.awt.Dimension(328, 40));
        jpventana4.setPreferredSize(new java.awt.Dimension(328, 40));

        jlcerrarResultado.setBackground(new java.awt.Color(0, 0, 0));
        jlcerrarResultado.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jlcerrarResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlcerrarResultado.setText("X");
        jlcerrarResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlcerrarResultadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlcerrarResultadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlcerrarResultadoMouseExited(evt);
            }
        });

        jltituloResultado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jltituloResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltituloResultado.setText("Resultado");

        javax.swing.GroupLayout jpventana4Layout = new javax.swing.GroupLayout(jpventana4);
        jpventana4.setLayout(jpventana4Layout);
        jpventana4Layout.setHorizontalGroup(
            jpventana4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpventana4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jltituloResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlcerrarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpventana4Layout.setVerticalGroup(
            jpventana4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlcerrarResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
            .addComponent(jltituloResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlmessageResultado1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(jpventana4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlmessageResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpventana4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlmessageResultado1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlmessageResultado)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ventanaResultadoLayout = new javax.swing.GroupLayout(ventanaResultado.getContentPane());
        ventanaResultado.getContentPane().setLayout(ventanaResultadoLayout);
        ventanaResultadoLayout.setHorizontalGroup(
            ventanaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ventanaResultadoLayout.setVerticalGroup(
            ventanaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBackground(new java.awt.Color(204, 204, 204));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setForeground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(300, 380));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 380));

        jpinterfaz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpinterfaz.setMaximumSize(new java.awt.Dimension(300, 380));
        jpinterfaz.setMinimumSize(new java.awt.Dimension(300, 380));
        jpinterfaz.setPreferredSize(new java.awt.Dimension(300, 380));

        jpventana.setBackground(new java.awt.Color(102, 102, 255));
        jpventana.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpventana.setMaximumSize(new java.awt.Dimension(300, 40));
        jpventana.setMinimumSize(new java.awt.Dimension(298, 40));
        jpventana.setName(""); // NOI18N
        jpventana.setPreferredSize(new java.awt.Dimension(299, 40));
        jpventana.setVerifyInputWhenFocusTarget(false);

        jltitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jltitulo.setText("Conversor");

        jlcerrarVentana.setBackground(new java.awt.Color(0, 0, 0));
        jlcerrarVentana.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jlcerrarVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlcerrarVentana.setText("X");
        jlcerrarVentana.setMaximumSize(new java.awt.Dimension(40, 30));
        jlcerrarVentana.setMinimumSize(new java.awt.Dimension(40, 30));
        jlcerrarVentana.setPreferredSize(new java.awt.Dimension(40, 30));
        jlcerrarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlcerrarVentanaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlcerrarVentanaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlcerrarVentanaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpventanaLayout = new javax.swing.GroupLayout(jpventana);
        jpventana.setLayout(jpventanaLayout);
        jpventanaLayout.setHorizontalGroup(
            jpventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpventanaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jltitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlcerrarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpventanaLayout.setVerticalGroup(
            jpventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpventanaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jlcerrarVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingresa grados en Celcius:");

        jtgrados.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtgrados.setAutoscrolls(false);

        jpaplicar.setBackground(new java.awt.Color(102, 102, 255));
        jpaplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpaplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpaplicarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpaplicarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpaplicarMouseExited(evt);
            }
        });

        jlaplicar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlaplicar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlaplicar.setText("Aplicar");

        javax.swing.GroupLayout jpaplicarLayout = new javax.swing.GroupLayout(jpaplicar);
        jpaplicar.setLayout(jpaplicarLayout);
        jpaplicarLayout.setHorizontalGroup(
            jpaplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaplicarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlaplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpaplicarLayout.setVerticalGroup(
            jpaplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaplicarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlaplicar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpinterfazLayout = new javax.swing.GroupLayout(jpinterfaz);
        jpinterfaz.setLayout(jpinterfazLayout);
        jpinterfazLayout.setHorizontalGroup(
            jpinterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpinterfazLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpinterfazLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jtgrados, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
            .addComponent(jpventana, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
            .addGroup(jpinterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpinterfazLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpaplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jpinterfazLayout.setVerticalGroup(
            jpinterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpinterfazLayout.createSequentialGroup()
                .addComponent(jpventana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtgrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
            .addGroup(jpinterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpinterfazLayout.createSequentialGroup()
                    .addContainerGap(324, Short.MAX_VALUE)
                    .addComponent(jpaplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpinterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpinterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jlcerrarVentanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarVentanaMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jlcerrarVentanaMouseClicked

    private void jlcerrarVentanaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarVentanaMouseEntered
        // TODO add your handling code here:
        jlcerrarVentana.setForeground(Color.white);
    }//GEN-LAST:event_jlcerrarVentanaMouseEntered

    private void jlcerrarVentanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarVentanaMouseExited
        // TODO add your handling code here:
        jlcerrarVentana.setForeground(Color.black);
    }//GEN-LAST:event_jlcerrarVentanaMouseExited

    private void jpaplicarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaplicarMouseEntered
        // TODO add your handling code here:
        String colorhex = "#6682FF";
        Color azulEdit = Color.decode(colorhex);
        jpaplicar.setBackground(azulEdit);
    }//GEN-LAST:event_jpaplicarMouseEntered

    private void jpaplicarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaplicarMouseExited
        // TODO add your handling code here:        
        String colorhex = "#6666FF";
        Color azulNormal = Color.decode(colorhex);
        jpaplicar.setBackground(azulNormal);
    }//GEN-LAST:event_jpaplicarMouseExited

    private void jpaplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaplicarMouseClicked
        // TODO add your handling code here:
        Pattern p = Pattern.compile("^\\d+(\\.\\d{1,2})?$");
        Matcher m = p.matcher(jtgrados.getText());
        if (!m.matches()) {
            ventanaError.setLocationRelativeTo(null);
            ventanaError.setVisible(true);
            jtgrados.setText("");
            jtgrados.requestFocus();
            return;
        }else{
            double num = Double.parseDouble(jtgrados.getText());
            double resultado = num * 9/5 + 32;
            ventanaResultado.setLocationRelativeTo(null);
            ventanaResultado.setVisible(true);
            jlmessageResultado.setText(resultado + "° Fahrenheit.");
        }
    }//GEN-LAST:event_jpaplicarMouseClicked

    private void jlcerrarResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarResultadoMouseClicked
        // TODO add your handling code here:
        ventanaResultado.dispose();
    }//GEN-LAST:event_jlcerrarResultadoMouseClicked

    private void jlcerrarResultadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarResultadoMouseEntered
        // TODO add your handling code here:
        jlcerrarResultado.setForeground(Color.white);
    }//GEN-LAST:event_jlcerrarResultadoMouseEntered

    private void jlcerrarResultadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarResultadoMouseExited
        // TODO add your handling code here:
        jlcerrarResultado.setForeground(Color.black);
    }//GEN-LAST:event_jlcerrarResultadoMouseExited

    private void jlcerrarErrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarErrorMouseClicked
        // TODO add your handling code here:
        ventanaError.dispose();
    }//GEN-LAST:event_jlcerrarErrorMouseClicked

    private void jlcerrarErrorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarErrorMouseEntered
        // TODO add your handling code here:
        jlcerrarError.setForeground(Color.white);
    }//GEN-LAST:event_jlcerrarErrorMouseEntered

    private void jlcerrarErrorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarErrorMouseExited
        // TODO add your handling code here:
        jlcerrarError.setForeground(Color.black);
    }//GEN-LAST:event_jlcerrarErrorMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlaplicar;
    private javax.swing.JLabel jlcerrarError;
    private javax.swing.JLabel jlcerrarResultado;
    private javax.swing.JLabel jlcerrarVentana;
    private javax.swing.JLabel jlmessageResultado;
    private javax.swing.JLabel jlmessageResultado1;
    private javax.swing.JLabel jltitulo;
    private javax.swing.JLabel jltituloError;
    private javax.swing.JLabel jltituloResultado;
    private javax.swing.JPanel jpaplicar;
    private javax.swing.JPanel jpinterfaz;
    private javax.swing.JPanel jpinterfazError;
    private javax.swing.JPanel jpventana;
    private javax.swing.JPanel jpventana3;
    private javax.swing.JPanel jpventana4;
    private javax.swing.JTextField jtgrados;
    private javax.swing.JDialog ventanaError;
    private javax.swing.JDialog ventanaResultado;
    // End of variables declaration//GEN-END:variables

}
