
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Jin
 */
public class ventana extends javax.swing.JFrame {

    int xMouse, yMouse;
    /**
     * Creates new form conversorPantalla
     */
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaError = new javax.swing.JDialog();
        jpinterfazError = new javax.swing.JPanel();
        jpventana3 = new javax.swing.JPanel();
        jlcerrarError = new javax.swing.JLabel();
        jltituloError = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ventanaResultado = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jlmessageResultado = new javax.swing.JLabel();
        jlmessageResultado1 = new javax.swing.JLabel();
        jpventana4 = new javax.swing.JPanel();
        jlcerrarResultado = new javax.swing.JLabel();
        jltituloResultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jpinterfazPrincipal = new javax.swing.JPanel();
        jpbarraTitulo = new javax.swing.JPanel();
        jlbotonCerrar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpbotonAplicar = new javax.swing.JPanel();
        jlbotonAplicar = new javax.swing.JLabel();
        jltextoInterfaz = new javax.swing.JLabel();
        jtgrados = new javax.swing.JTextField();

        ventanaError.setAlwaysOnTop(true);
        ventanaError.setBackground(new java.awt.Color(204, 204, 204));
        ventanaError.setModal(true);
        ventanaError.setUndecorated(true);
        ventanaError.setResizable(false);
        ventanaError.setSize(new java.awt.Dimension(330, 100));
        ventanaError.setType(java.awt.Window.Type.POPUP);

        jpinterfazError.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpinterfazError.setForeground(new java.awt.Color(204, 204, 204));
        jpinterfazError.setMaximumSize(new java.awt.Dimension(330, 100));
        jpinterfazError.setMinimumSize(new java.awt.Dimension(329, 99));
        jpinterfazError.setOpaque(false);
        jpinterfazError.setPreferredSize(new java.awt.Dimension(330, 100));
        jpinterfazError.setVerifyInputWhenFocusTarget(false);

        jpventana3.setBackground(new java.awt.Color(255, 51, 51));
        jpventana3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpventana3.setAlignmentX(0.0F);
        jpventana3.setAlignmentY(0.0F);
        jpventana3.setMaximumSize(new java.awt.Dimension(300, 40));
        jpventana3.setMinimumSize(new java.awt.Dimension(300, 40));
        jpventana3.setPreferredSize(new java.awt.Dimension(300, 40));

        jlcerrarError.setBackground(new java.awt.Color(0, 0, 0));
        jlcerrarError.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jlcerrarError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlcerrarError.setText("X");
        jlcerrarError.setMaximumSize(new java.awt.Dimension(40, 30));
        jlcerrarError.setMinimumSize(new java.awt.Dimension(40, 30));
        jlcerrarError.setPreferredSize(new java.awt.Dimension(40, 30));
        jlcerrarError.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlcerrarErrorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlcerrarErrorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlcerrarErrorMouseExited(evt);
            }
        });

        jltituloError.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jltituloError.setText("Error");

        javax.swing.GroupLayout jpventana3Layout = new javax.swing.GroupLayout(jpventana3);
        jpventana3.setLayout(jpventana3Layout);
        jpventana3Layout.setHorizontalGroup(
            jpventana3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpventana3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jltituloError, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(jlcerrarError, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpventana3Layout.setVerticalGroup(
            jpventana3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpventana3Layout.createSequentialGroup()
                .addComponent(jlcerrarError, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addComponent(jltituloError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingresa grados a convertir con o sin punto.");
        jLabel2.setToolTipText("Ejemplo: 32.6 o 32");

        javax.swing.GroupLayout jpinterfazErrorLayout = new javax.swing.GroupLayout(jpinterfazError);
        jpinterfazError.setLayout(jpinterfazErrorLayout);
        jpinterfazErrorLayout.setHorizontalGroup(
            jpinterfazErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpinterfazErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpinterfazErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpventana3, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
        );
        jpinterfazErrorLayout.setVerticalGroup(
            jpinterfazErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpinterfazErrorLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
            .addGroup(jpinterfazErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpinterfazErrorLayout.createSequentialGroup()
                    .addComponent(jpventana3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 58, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout ventanaErrorLayout = new javax.swing.GroupLayout(ventanaError.getContentPane());
        ventanaError.getContentPane().setLayout(ventanaErrorLayout);
        ventanaErrorLayout.setHorizontalGroup(
            ventanaErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpinterfazError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ventanaErrorLayout.setVerticalGroup(
            ventanaErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpinterfazError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ventanaResultado.setAlwaysOnTop(true);
        ventanaResultado.setBackground(new java.awt.Color(204, 204, 204));
        ventanaResultado.setMinimumSize(new java.awt.Dimension(330, 115));
        ventanaResultado.setUndecorated(true);
        ventanaResultado.setResizable(false);
        ventanaResultado.setSize(new java.awt.Dimension(330, 115));
        ventanaResultado.setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(330, 115));
        jPanel1.setMinimumSize(new java.awt.Dimension(330, 115));
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 115));

        jlmessageResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlmessageResultado.setText("hola");

        jlmessageResultado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlmessageResultado1.setText("Se convirtieron los grados Celsius a Fahrenheit");

        jpventana4.setBackground(new java.awt.Color(102, 102, 255));
        jpventana4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpventana4.setMaximumSize(new java.awt.Dimension(330, 40));
        jpventana4.setMinimumSize(new java.awt.Dimension(328, 40));
        jpventana4.setPreferredSize(new java.awt.Dimension(328, 40));

        jlcerrarResultado.setBackground(new java.awt.Color(0, 0, 0));
        jlcerrarResultado.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jlcerrarResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlcerrarResultado.setText("X");
        jlcerrarResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlcerrarResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlcerrarResultadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlcerrarResultadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlcerrarResultadoMouseExited(evt);
            }
        });

        jltituloResultado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jltituloResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltituloResultado.setText("Resultado");

        javax.swing.GroupLayout jpventana4Layout = new javax.swing.GroupLayout(jpventana4);
        jpventana4.setLayout(jpventana4Layout);
        jpventana4Layout.setHorizontalGroup(
            jpventana4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpventana4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jltituloResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlcerrarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpventana4Layout.setVerticalGroup(
            jpventana4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlcerrarResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
            .addComponent(jltituloResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlmessageResultado1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(jpventana4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlmessageResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpventana4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlmessageResultado1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlmessageResultado)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ventanaResultadoLayout = new javax.swing.GroupLayout(ventanaResultado.getContentPane());
        ventanaResultado.getContentPane().setLayout(ventanaResultadoLayout);
        ventanaResultadoLayout.setHorizontalGroup(
            ventanaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ventanaResultadoLayout.setVerticalGroup(
            ventanaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(204, 204, 204));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setForeground(new java.awt.Color(204, 204, 204));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(300, 380));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpinterfazPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        jpinterfazPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jpbarraTitulo.setBackground(new java.awt.Color(102, 102, 255));
        jpbarraTitulo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jpbarraTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpbarraTituloMouseDragged(evt);
            }
        });
        jpbarraTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpbarraTituloMousePressed(evt);
            }
        });

        jlbotonCerrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlbotonCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbotonCerrar.setText("X");
        jlbotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbotonCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbotonCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbotonCerrarMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Krub Medium", 0, 18)); // NOI18N
        jLabel3.setText("Conversor");

        javax.swing.GroupLayout jpbarraTituloLayout = new javax.swing.GroupLayout(jpbarraTitulo);
        jpbarraTitulo.setLayout(jpbarraTituloLayout);
        jpbarraTituloLayout.setHorizontalGroup(
            jpbarraTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpbarraTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpbarraTituloLayout.setVerticalGroup(
            jpbarraTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpbarraTituloLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpbarraTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpbotonAplicar.setBackground(new java.awt.Color(102, 102, 255));
        jpbotonAplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpbotonAplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpbotonAplicarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpbotonAplicarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpbotonAplicarMouseExited(evt);
            }
        });

        jlbotonAplicar.setFont(new java.awt.Font("Krub Light", 1, 18)); // NOI18N
        jlbotonAplicar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbotonAplicar.setText("Aplicar");

        javax.swing.GroupLayout jpbotonAplicarLayout = new javax.swing.GroupLayout(jpbotonAplicar);
        jpbotonAplicar.setLayout(jpbotonAplicarLayout);
        jpbotonAplicarLayout.setHorizontalGroup(
            jpbotonAplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpbotonAplicarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbotonAplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpbotonAplicarLayout.setVerticalGroup(
            jpbotonAplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpbotonAplicarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbotonAplicar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jltextoInterfaz.setFont(new java.awt.Font("Krub Light", 0, 18)); // NOI18N
        jltextoInterfaz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltextoInterfaz.setText("Ingresa grados a convertir");

        jtgrados.setFont(new java.awt.Font("Krub Medium", 0, 18)); // NOI18N
        jtgrados.setForeground(new java.awt.Color(51, 51, 51));
        jtgrados.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtgrados.setBorder(null);
        jtgrados.setCaretColor(new java.awt.Color(204, 204, 204));
        jtgrados.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jtgrados.setSelectedTextColor(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpinterfazPrincipalLayout = new javax.swing.GroupLayout(jpinterfazPrincipal);
        jpinterfazPrincipal.setLayout(jpinterfazPrincipalLayout);
        jpinterfazPrincipalLayout.setHorizontalGroup(
            jpinterfazPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpbarraTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpinterfazPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpinterfazPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jltextoInterfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpbotonAplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpinterfazPrincipalLayout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addComponent(jtgrados, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addContainerGap())
        );
        jpinterfazPrincipalLayout.setVerticalGroup(
            jpinterfazPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpinterfazPrincipalLayout.createSequentialGroup()
                .addComponent(jpbarraTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jltextoInterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtgrados, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jpbotonAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jpinterfazPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jlcerrarResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarResultadoMouseClicked
        // TODO add your handling code here:
        ventanaResultado.dispose();
    }//GEN-LAST:event_jlcerrarResultadoMouseClicked

    private void jlcerrarResultadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarResultadoMouseEntered
        // TODO add your handling code here:
        jlcerrarResultado.setForeground(Color.white);
        jtgrados.setText("");
    }//GEN-LAST:event_jlcerrarResultadoMouseEntered

    private void jlcerrarResultadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarResultadoMouseExited
        // TODO add your handling code here:
        jlcerrarResultado.setForeground(Color.black);
    }//GEN-LAST:event_jlcerrarResultadoMouseExited

    private void jlcerrarErrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarErrorMouseClicked
        // TODO add your handling code here:
        ventanaError.dispose();
    }//GEN-LAST:event_jlcerrarErrorMouseClicked

    private void jlcerrarErrorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarErrorMouseEntered
        // TODO add your handling code here:
        jlcerrarError.setForeground(Color.white);
    }//GEN-LAST:event_jlcerrarErrorMouseEntered

    private void jlcerrarErrorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlcerrarErrorMouseExited
        // TODO add your handling code here:
        jlcerrarError.setForeground(Color.black);
    }//GEN-LAST:event_jlcerrarErrorMouseExited

    private void jlbotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbotonCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jlbotonCerrarMouseClicked

    private void jpbarraTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpbarraTituloMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jpbarraTituloMousePressed

    private void jpbarraTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpbarraTituloMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation( x - xMouse, y - yMouse);
    }//GEN-LAST:event_jpbarraTituloMouseDragged

    private void jlbotonCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbotonCerrarMouseEntered
        jlbotonCerrar.setForeground(Color.white);
        
    }//GEN-LAST:event_jlbotonCerrarMouseEntered

    private void jlbotonCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbotonCerrarMouseExited
        jlbotonCerrar.setForeground(Color.black);
    }//GEN-LAST:event_jlbotonCerrarMouseExited

    private void jpbotonAplicarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpbotonAplicarMouseEntered
        jpbotonAplicar.setBackground(new Color(115, 115, 255));
    }//GEN-LAST:event_jpbotonAplicarMouseEntered

    private void jpbotonAplicarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpbotonAplicarMouseExited
        jpbotonAplicar.setBackground(new Color(102, 102, 255));
    }//GEN-LAST:event_jpbotonAplicarMouseExited

    private void jpbotonAplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpbotonAplicarMouseClicked
        Pattern p = Pattern.compile("^\\d+(\\.\\d{1,2})?$");
        Matcher m = p.matcher(jtgrados.getText());
        if (!m.matches()) {
            ventanaError.setLocationRelativeTo(null);
            ventanaError.setVisible(true);
            jtgrados.setText("");
            jtgrados.requestFocus();
            return;
        }else{
            double num = Double.parseDouble(jtgrados.getText());
            double resultado = num * 9/5 + 32;
            ventanaResultado.setLocationRelativeTo(null);
            ventanaResultado.setVisible(true);
            jlmessageResultado.setText(resultado + "° Fahrenheit.");
        }
    }//GEN-LAST:event_jpbotonAplicarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbotonAplicar;
    private javax.swing.JLabel jlbotonCerrar;
    private javax.swing.JLabel jlcerrarError;
    private javax.swing.JLabel jlcerrarResultado;
    private javax.swing.JLabel jlmessageResultado;
    private javax.swing.JLabel jlmessageResultado1;
    private javax.swing.JLabel jltextoInterfaz;
    private javax.swing.JLabel jltituloError;
    private javax.swing.JLabel jltituloResultado;
    private javax.swing.JPanel jpbarraTitulo;
    private javax.swing.JPanel jpbotonAplicar;
    private javax.swing.JPanel jpinterfazError;
    private javax.swing.JPanel jpinterfazPrincipal;
    private javax.swing.JPanel jpventana3;
    private javax.swing.JPanel jpventana4;
    private javax.swing.JTextField jtgrados;
    private javax.swing.JDialog ventanaError;
    private javax.swing.JDialog ventanaResultado;
    // End of variables declaration//GEN-END:variables

}
